name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: 'Test'
        env:
          COSMOS_ENDPOINT: ${{secrets.COSMOS_ENDPOINT}}
          COSMOS_KEY: ${{secrets.COSMOS_KEY}}
          COSMOS_DATABASE: ${{secrets.COSMOS_DATABASE}}
          COSMOS_CONTAINER: ${{secrets.COSMOS_CONTAINER}}
        run: npm test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
